"""Initial migration for Game and Player models

Revision ID: ceb69514d7c0
Revises: 
Create Date: 2024-12-17 18:03:02.107603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceb69514d7c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('queue_type', sa.String(), nullable=False),
    sa.Column('player_count', sa.Integer(), nullable=False),
    sa.Column('human_count', sa.Integer(), nullable=False),
    sa.Column('game_length', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id')
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('player_slot', sa.Integer(), nullable=False),
    sa.Column('legion', sa.String(), nullable=False),
    sa.Column('game_result', sa.String(), nullable=False),
    sa.Column('overall_elo', sa.Float(), nullable=False),
    sa.Column('classic_elo', sa.Float(), nullable=False),
    sa.Column('party_size', sa.Integer(), nullable=False),
    sa.Column('eco', sa.Float(), nullable=False),
    sa.Column('legion_elo', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id')
    )
    op.create_table('match_players',
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['game.match_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], ),
    sa.PrimaryKeyConstraint('match_id', 'player_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_players')
    op.drop_table('player')
    op.drop_table('game')
    # ### end Alembic commands ###
